### PR TITLE
Update images and manifest to match HomeWizard branding

### PR DESCRIPTION
**Pull request by DCSBL**
SSIA

I don't know how to test if all images are rendered as expected, so please do! Feel free to ask me if you need any adjustments.

### CODE REVIEW

**Comment by jtebbens** [comment]
Hi, I've to test and verify as some are svg files which work or dont work (yes I had struggled before on svg without understanding the reason of the problem). Further the small and large icons/images must be a fixed size 70px and 150px if I am correct but have to review those as well.

**Comment by DCSBL** [comment]
Thanks!

> Further the small and large icons/images must be a fixed size 70px and 150px if I am correct but have to review those as well.

I've tried to honor the sizes mentioned in https://apps.developer.homey.app/app-store/guidelines#id-1.4.-images

**Review by jtebbens — APPROVED** [review]

**Comment by DCSBL** [comment]
Is there any documentation how this is determined? We do not really agree to this statement.

image

**Comment by jtebbens** [comment]
This comes from the homey install nodejs (internal check). I merged your adjustment and tried to test/install it to my Homey which ended up with the error I shared. I guess you have to talk to Athom about this. I think Abe Haverkamp might be the right person about this.

**Pull request merged**
